routes:
  amazon:
    uses: index
    as: amazon.index
  saugroboter:
    uses: getSaugroboter
    as: amazon.saugroboter
  export:
    uses: export
    as: amazon.export
  maehroboter:
    uses: getMaehroboter
    as: amazon.maehroboter
